draft_creation_task:
  description: >
    Marcus, use ONLY the RAG Tool to extract insights and create a content blueprint for "{topic}".
    
    **Requirements:**
    - Query RAG Tool extensively about {topic}
    - Ask: "What are the latest trends in {topic}?"
    - Ask: "What are the benefits and challenges of {topic}?"
    - Ask: "What do experts say about {topic}?"
    - Ask: "What are practical applications of {topic}?"
    
    **Content Planning:**
    - Approximate word count: {word_count} words
    - Target read time: {read_time} minutes
    - Create engaging content suitable for diverse audiences
    - Plan for dev.to publishing platform (tech-friendly but accessible)


  expected_output: >
    Content blueprint (500-600 words) with:
    
    **Content Strategy:**
    - Main narrative angle for {topic}
    - Value proposition for readers
    - Content approach (technical/accessible balance)
    
    **Detailed Outline:**
    1. Engaging opening hook and introduction
    2. 5-7 main sections with:
       - Compelling section titles
       - Key points to cover (2-3 per section)
       - Supporting evidence from RAG research
       - Estimated word distribution to reach ~{word_count} words
    3. Strong conclusion with engagement elements
    
    **Content Elements:**
    - Key statistics and insights to highlight
    - Expert quotes or opinions to include
    - Real-world examples or case studies
    - Practical takeaways for readers
    - Structure for ~{read_time} minute read time

final_writing_task:
  description: >
    Elena, write a complete, SEO-optimized blog post about "{topic}" using the provided draft as your primary guide.

    **PRIMARY APPROACH:**
    - Use the draft creation task output as your main content source
    - Enhance and expand the draft into a polished, SEO-friendly blog post
    - Only use RAG Tool for specific fact-checking or additional details

    **COVER IMAGE REQUIREMENTS:**
    - Use the Dev.to Cover Image Finder tool to find a suitable cover image
    - Search for images related to "{topic}"
    - If no suitable topic-specific image found, tool will automatically fallback to tech images
    - Include the cover image URL in the frontmatter ONLY
    - DO NOT embed the cover image again in the article body
    - DO NOT include image attribution in the article content


    **SEO OPTIMIZATION REQUIREMENTS:**
    
    *Title & Meta Optimization:*
    - Create an SEO-optimized title (50-60 characters) that includes primary keyword
    - Write a compelling meta description (150-160 characters) with target keywords
    - Use power words like "Complete Guide", "Ultimate", "Essential", "Best Practices"
    
    *Keyword Strategy:*
    - Identify and naturally integrate primary keyword throughout the content
    - Use 2-3 secondary keywords/related terms
    - Include keywords in: title, first paragraph, headings, and naturally throughout
    - Aim for 1-2% keyword density (don't overstuff)
    
    **CONTENT STRUCTURE REQUIREMENTS:**
    - Do NOT include an H1 heading in the markdown content body
    - The title exists only in the frontmatter
    - Start content directly with an engaging opening paragraph
    - Use H2 (##) for main sections, H3 (###) for subsections
    - Include target keywords in at least 2-3 H2 headings

    *Technical SEO Elements:*
    - Include relevant dev.to tags (4-5 tags maximum)
    - Use internal linking opportunities where natural
    - Add alt text concepts for any referenced images
    - Ensure mobile-friendly formatting
    
    *Content Quality Signals:*
    - Start with a hook that addresses reader's pain point or question
    - Include actionable insights and practical examples
    - Use data, statistics, or concrete examples when possible
    - Address common questions or objections in the content
    - Write for both beginners and experienced developers where applicable

    **ENDING REQUIREMENT:**
    - Instead of a 'reference links' or 'internal linking' section, finish with a short, impactful conclusion
    - The conclusion should summarize key takeaways and include a clear call-to-action
    - End with an engaging question or challenge for readers

  expected_output: >
    ONLY publish-ready markdown content for a dev.to blog post with comprehensive SEO optimization.
    Must include:
    - SEO-optimized title (50-60 characters) with primary keyword
    - SEO-friendly meta description (150-160 characters) with target keywords  
    - 4-5 relevant tags for dev.to
    - **cover_image:** URL from Pexels search (frontmatter only)
    - Clear heading structure (H2 for main sections, H3 for subsections) - NO H1 heading in content
    - Short, scannable paragraphs with bullet points and lists
    - Natural keyword integration throughout content
    - Actionable insights and practical examples
    - End with an engaging, concise conclusion with call-to-action (not reference links)
    
    IMPORTANT: Do NOT include an H1 heading (# Title) in the markdown content body. The title should ONLY appear in the frontmatter. Start the content directly with an engaging opening paragraph, then use H2 (##) for main sections.

      

publishing_task:
  description: >
    Use the Dev.to Publisher tool to publish the completed blog post on Dev.to.

    - Take the blog markdown file from the Senior Writer as input.
    - Use the Dev.to Publisher tool to extract title, tags, and cover image from the frontmatter and submit the post.
    - Set publishing status to 'published' by default.
    - If publishing fails, include clear error reporting in the output.

  expected_output: >
    JSON result of the publishing attempt, including the Dev.to URL if published successfully. Must include:
    - The article URL on Dev.to
    - Article ID on Dev.to
    - Published status
    - Any error details if publishing failed
