draft_creation_task:
  description: >
    Marcus, use ONLY the RAG Tool to extract insights and create a content blueprint for "{topic}".
    
    **Requirements:**
    - Query RAG Tool extensively about {topic}
    - Ask: "What are the latest trends in {topic}?"
    - Ask: "What are the benefits and challenges of {topic}?"
    - Ask: "What do experts say about {topic}?"
    - Ask: "What are practical applications of {topic}?"
    
    **Content Planning:**
    - Approximate word count: {word_count} words
    - Target read time: {read_time} minutes
    - Create engaging content suitable for diverse audiences
    - Plan for dev.to publishing platform (tech-friendly but accessible)


  expected_output: >
    Content blueprint (500-600 words) with:
    
    **Content Strategy:**
    - Main narrative angle for {topic}
    - Value proposition for readers
    - Content approach (technical/accessible balance)
    
    **Detailed Outline:**
    1. Engaging opening hook and introduction
    2. 5-7 main sections with:
       - Compelling section titles
       - Key points to cover (2-3 per section)
       - Supporting evidence from RAG research
       - Estimated word distribution to reach ~{word_count} words
    3. Strong conclusion with engagement elements
    
    **Content Elements:**
    - Key statistics and insights to highlight
    - Expert quotes or opinions to include
    - Real-world examples or case studies
    - Practical takeaways for readers
    - Structure for ~{read_time} minute read time

final_writing_task:
  description: >
    Elena, write a complete blog post about "{topic}" using the provided draft as your primary guide.

    **PRIMARY APPROACH:**
    - Use the draft creation task output as your main content source
    - Enhance and expand the draft into a polished blog post
    - Only use RAG Tool for specific fact-checking or additional details

    **COVER IMAGE REQUIREMENTS:**
    - Use the Dev.to Cover Image Finder tool to find a suitable cover image
    - Search for images related to "{topic}"
    - If no suitable topic-specific image found, tool will automatically fallback to tech images
    - Include the cover image URL in the frontmatter

    **ENDING REQUIREMENT:**
    - Instead of a 'reference links' or 'internal linking' section, finish the blog with a short, impactful conclusion. 
    - The conclusion should summarize the main points and leave the reader with a clear final thought or call to action.

    **SEO REQUIREMENTS:**
    - Write with SEO in mind: include clear headings (H1, H2, H3), use target keywords naturally
    - Ensure meta description is concise, compelling, and keyword-rich
    - Use short paragraphs, bullet points, and numbered lists where useful

  expected_output: >
    ONLY publish-ready markdown content for a dev.to blog post with cover image.
    Must include:
    - SEO-optimized title
    - SEO-friendly meta description  
    - Proper tags
    - **cover_image:** URL from Pexels search
    - Attribution for cover image in the article
    - End with an engaging, concise conclusion in the final paragraph (not with a reference links section)

    Your final answer MUST be a fully SEO-optimized dev.to article in markdown format, ending with a short, strong conclusion.


publishing_task:
  description: >
    Use the Dev.to Publisher tool to publish the completed blog post on Dev.to.

    - Take the blog markdown file from the Senior Writer as input.
    - Use the Dev.to Publisher tool to extract title, tags, and cover image from the frontmatter and submit the post.
    - Set publishing status to 'published' by default.
    - If publishing fails, include clear error reporting in the output.

  expected_output: >
    JSON result of the publishing attempt, including the Dev.to URL if published successfully. Must include:
    - The article URL on Dev.to
    - Article ID on Dev.to
    - Published status
    - Any error details if publishing failed
